INSERT INTO ACCOUNTS (ACCOUNT_ID, ACCT_FULLNAME) VALUES ('1000101','John Doe');
INSERT INTO ACCOUNTS (ACCOUNT_ID, ACCT_FULLNAME) VALUES ('1000102','Alex Murphy');
INSERT INTO ACCOUNTS (ACCOUNT_ID, ACCT_FULLNAME) VALUES ('1000103','Tom Cruise');
INSERT INTO ACCOUNTS (ACCOUNT_ID, ACCT_FULLNAME) VALUES ('1000103','Mary Crow');
