INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (101,CURRENT_DATE,'Real Estae',130000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (201,CURRENT_DATE,'Comodities : Gold',31000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (202,CURRENT_DATE,'Comodities : Silver',4200);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (301,CURRENT_DATE,'Bonds',19000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (302,CURRENT_DATE,'FIxed Income',2200);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (401,CURRENT_DATE,'MF',16000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (402,CURRENT_DATE,'ETF',2400);
