INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (101,SYSDATE,'Real Estae',110000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (201,SYSDATE,'Comodities : Gold',30000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (202,SYSDATE,'Comodities : Silver',4000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (301,SYSDATE,'Bonds',20000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (302,SYSDATE,'FIxed Income',2500);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (401,SYSDATE,'MF',18000);
INSERT INTO ASSETS (ASSET_ID,BUSINESS_DT,DESCRIPTION,USD_PRICE)
VALUES (402,SYSDATE,'ETF',2200);
