-- This script is to create ASSETS table to store customer assets information
CREATE TABLE ASSETS
(
    ASSET_ID NUMBER,
    BUSINESS_DT DATE NOT NULL,
    DESCRIPTION VARCHAR2(4000),
    USD_PRICE NUMBER NOT NULL,
    CONSTRAINT ASSETS_PK PRIMARY KEY (ASSET_ID,BUSINESS_DT)
);
/