-- This script is to create ACCOUNT_ASSET_MAP table
-- It store's mapping between customer account and assets the account hold.
CREATE TABLE ACCOUNT_ASSET_MAP
(
    ACCT_AST_MAP_ID integer,
    ACCOUNT_ID integer,
    BUSINESS_DT DATE NOT NULL,
    ACTIVE_IND character(1) DEFAULT 'Y',
    MAP_FROM_TMSTMP TIMESTAMP NOT NULL,
    MAP_TO_TMSTMP TIMESTAMP DEFAULT NULL,
    INSERT_TMSTMP TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATE_TMSTMP TIMESTAMP DEFAULT NOW() NOT NULL,
    CONSTRAINT ACCT_AST_MAP_PK PRIMARY KEY (ACCT_AST_MAP_ID),
    CONSTRAINT ACCOUNT_FK FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID),
    CONSTRAINT ACCT_AST_MAP_CK CHECK (ACTIVE_IND IN ('Y','N'))
);
