-- This script is to create ASSET_ALLOCATION table
-- It stores list of assets held by an account
CREATE TABLE ASSET_ALLOCATION
(
    ASSET_ALLOC_ID serial PRIMARY KEY,
    ACCT_AST_MAP_ID integer,
    ASSET_ID integer NOT NULL,
    CONSTRAINT AST_ALLOC_UNQ_KEY unique (ACCT_AST_MAP_ID,ASSET_ID),
    CONSTRAINT ACCT_AST_FK FOREIGN KEY (ACCT_AST_MAP_ID) REFERENCES ACCOUNT_ASSET_MAP (ACCT_AST_MAP_ID)
);
